"""Introduction and Topological Setup

Introduces a topology $\\tau$ on the set of positive integers $\\mathbb{N}$,
generated by the base $\\beta = \\{\\sigma_n : n \\in \\mathbb{N}\\}$ where
$\\sigma_n = \\{m \\in \\mathbb{N} : \\gcd(n, m) = 1\\}$. Establishes that
$\\beta$ is a valid topological base and records well-known mathematical facts
used in subsequent proofs.
"""
from gaia.lang import claim, setting, deduction

# ── Definitions (Settings) ─────────────────────────────────────────────

s_positive_integers = setting(
    "Let $\\mathbb{N}$ denote the set of positive integers $\\{1, 2, 3, \\ldots\\}$.",
    title="Positive integers N",
)

s_coprimality_set = setting(
    "For each $n \\in \\mathbb{N}$, define "
    "$\\sigma_n := \\{m \\in \\mathbb{N} : \\gcd(n, m) = 1\\}$, "
    "the set of positive integers coprime to $n$. "
    "In particular, $\\sigma_1 = \\mathbb{N}$.",
    title="Coprimality sets sigma_n",
)

s_base_and_topology = setting(
    "Define $\\beta := \\{\\sigma_n : n \\in \\mathbb{N}\\}$. "
    "The topology $\\tau$ on $\\mathbb{N}$ is the topology generated by "
    "$\\beta$ as a base. The topological space is denoted "
    "$X := (\\mathbb{N}, \\tau)$.",
    title="Base beta and topology tau on N",
)

s_primes_and_multiples = setting(
    "Let $P$ denote the set of prime numbers. For any prime $p$, define "
    "$M_p := \\{kp : k \\in \\mathbb{N}\\}$, the set of all positive multiples of $p$.",
    title="Primes P and multiples M_p",
)

s_subspace = setting(
    "Define $N_1 := \\mathbb{N} \\setminus \\{1\\}$ and equip it with the subspace "
    "topology $\\tau_1 := \\{N_1 \\cap O : O \\in \\tau\\}$, generated by the base "
    "$\\beta_1 := \\{N_1 \\cap \\sigma_n : \\sigma_n \\in \\beta\\}$. "
    "The topological subspace is denoted $X_1 := (N_1, \\tau_1)$.",
    title="Subspace X_1 = (N_1, tau_1)",
)

# ── Well-known mathematical facts (leaf claims) ───────────────────────

gcd_multiplicativity = claim(
    "For all positive integers $x, n, m$: $\\gcd(x, n) = 1$ and $\\gcd(x, m) = 1$ "
    "if and only if $\\gcd(x, nm) = 1$. "
    "As a consequence, $\\sigma_{nm} = \\sigma_n \\cap \\sigma_m$ for all "
    "$n, m \\in \\mathbb{N}$.",
    title="GCD multiplicativity",
    background=[s_coprimality_set, s_positive_integers],
)

fundamental_theorem_arithmetic = claim(
    "Every integer $n > 1$ can be expressed as a product of prime numbers "
    "(Fundamental Theorem of Arithmetic). Equivalently, every integer greater "
    "than 1 is divisible by at least one prime, so "
    "$\\bigcup_{p \\in P} M_p = \\mathbb{N} \\setminus \\{1\\}$.",
    title="Fundamental Theorem of Arithmetic",
    background=[s_primes_and_multiples, s_positive_integers],
)

closure_union_containment = claim(
    "In any topological space $(Y, \\mathcal{T})$, for any collection of subsets "
    "$\\{A_\\alpha\\}$, the union of closures is contained in the closure of the union: "
    "$\\bigcup_{\\alpha} \\operatorname{cl}_Y(A_\\alpha) "
    "\\subseteq \\operatorname{cl}_Y\\!\\left(\\bigcup_{\\alpha} A_\\alpha\\right)$.",
    title="Union of closures is contained in closure of union",
)

density_transitivity = claim(
    "In topological spaces, density is transitive: if $A$ is dense in subspace $B$ "
    "and $B$ is dense in ambient space $C$, then $A$ is dense in $C$.",
    title="Transitivity of density",
)

# ── Paper result: Theorem 0.1 ─────────────────────────────────────────

thm_base = claim(
    "$\\beta = \\{\\sigma_n : n \\in \\mathbb{N}\\}$ is a base for some topology "
    "on $\\mathbb{N}$. This holds because "
    "(1) $\\bigcup_{n \\in \\mathbb{N}} \\sigma_n = \\sigma_1 = \\mathbb{N}$, and "
    "(2) for all $n, m \\in \\mathbb{N}$, "
    "$\\sigma_{nm} = \\sigma_n \\cap \\sigma_m \\in \\beta$, "
    "so the intersection of any two base elements contains a base element.",
    title="Theorem 0.1: beta is a topological base",
    background=[s_coprimality_set, s_base_and_topology, s_positive_integers],
    source="arXiv:2402.03356, Theorem 0.1",
)

deduction(
    [gcd_multiplicativity],
    thm_base,
    reason=(
        "By @gcd_multiplicativity, $\\sigma_{nm} = \\sigma_n \\cap \\sigma_m$ for all "
        "$n, m \\in \\mathbb{N}$. This gives condition (2) for a topological base: the "
        "intersection of any two base elements $\\sigma_n \\cap \\sigma_m = \\sigma_{nm}$ "
        "is itself in $\\beta$. Condition (1) is immediate: "
        "$\\bigcup_{n} \\sigma_n \\supseteq \\sigma_1 = \\mathbb{N}$. "
        "Together, these two conditions establish that $\\beta$ is a base for a topology on $\\mathbb{N}$."
    ),
    background=[s_coprimality_set, s_base_and_topology, s_positive_integers],
)

# ── Remark 0.2 properties ─────────────────────────────────────────────

sigma_n_infinite = claim(
    "For every positive integer $n$, the set "
    "$\\sigma_n = \\{m \\in \\mathbb{N} : \\gcd(n, m) = 1\\}$ is infinite. "
    "For $n > 1$, $\\sigma_n$ consists of all positive integers in the residue "
    "classes $m \\pmod{n}$ with $\\gcd(m, n) = 1$; each such arithmetic "
    "progression $\\{m, m+n, m+2n, \\ldots\\}$ is infinite.",
    title="Remark 0.2: sigma_n is infinite",
    background=[s_coprimality_set, s_positive_integers],
)

tau_coarser_golomb = claim(
    "The topology $\\tau$ on $\\mathbb{N}$ generated by "
    "$\\beta = \\{\\sigma_n\\}$ is strictly coarser than Golomb's topology "
    "on $\\mathbb{N}$ (which uses arithmetic progressions $\\{a + nd : n \\geq 0\\}$ "
    "with $\\gcd(a, d) = 1$ as a base).",
    title="Remark 0.2: tau is strictly coarser than Golomb's topology",
    background=[s_base_and_topology],
)

# ── Properties of X (stated without proof, from reference [2]) ────────

x_not_t0 = claim(
    "The topological space $X = (\\mathbb{N}, \\tau)$ does not satisfy the "
    "$T_0$ separation axiom: there exist distinct points in $\\mathbb{N}$ that "
    "cannot be topologically distinguished by any open set in $\\tau$.",
    title="X is not T_0",
    background=[s_base_and_topology],
)

x_hyperconnected = claim(
    "The topological space $X = (\\mathbb{N}, \\tau)$ is hyperconnected: "
    "every two non-empty open sets in $\\tau$ have non-empty intersection.",
    title="X is hyperconnected",
    background=[s_base_and_topology],
)

x_ultraconnected = claim(
    "The topological space $X = (\\mathbb{N}, \\tau)$ is ultraconnected: "
    "every two non-empty closed sets in $\\tau$ have non-empty intersection.",
    title="X is ultraconnected",
    background=[s_base_and_topology],
)
